# Global configurations for all services
global:
  imagePullPolicy: IfNotPresent

# Chart-service configuration
chartService:
  image:
    repository: chart-service
    tag: 1.0.0

# MinIO configuration
minio:
  image:
    repository: minio/minio
    tag: latest

# Ollama configuration
ollama:
  image:
    repository: ollama/ollama
    tag: 2.1.0
